### PR TITLE
Search for a council by name and/or postcode

### LINKED ISSUE #177: [CCL] Header search box
- [x] Submits to a URL that handles postcodes, and either redirects to the council individual page, or shows a disambiguation page with all councils serving that postcode. (@zarino / @struan)
- [x] JavaScript autocomplete displays matching council names, once 3 or more characters are entered, clicking a result takes you to the council’s individual page (@zarino)

### PR DESCRIPTION
**Pull request by zarino**
Fixes #177.

Search boxes on the homepage and in the site navbar take a postcode and either redirect you to the (one) council which covers that location, or shows a disambiguation page with the two/three councils to choose from.

JavaScript enhancement that allows you to type a council name into the box, and shows matching councils in an autocomplete dropdown menu. Selecting a council from the menu (by clicking, or with the arrow keys + Enter) takes you to the page for that council.

*Note:* I also did some renaming and moving of the views and templates for the "council answers" and "question answers" pages, because it made the `/location` endpoint redirection slightly simpler, and the current state of affairs was also just a generally crappy thing that I’ve been meaning to tidy up for a long time. But this _will_ mean that, once this has been merged, there might be a few bumpy rebases required for other in-flight pull requests that modify those two pages.

# Postcode covered by two councils

Screenshot 2022-01-13 at 15-26-30 SCORING

# Postcode covered by three councils

Screenshot 2022-01-13 at 15-26-03 SCORING

# Invalid search term (not a postcode)

Screenshot 2022-01-13 at 15-27-02 SCORING

### CODE REVIEW

**Comment by struan** [comment]
If the search box isn't selected when you hover over it, the text becomes unreadable:

https://user-images.githubusercontent.com/5310/149768014-35b61e9f-5de5-4577-acad-537dca93a59d.mov

**Comment by lucascumsille** [comment]
> search box isn't selected when you hover over it

Are you planning to do the change on this pull request @zarino or I can add it to the #240 ?

**Review by struan — APPROVED** [review]
This looks good, modulo the blanking search box issue.

I've pushed a fixup that reduces the duplication between the two apps.

**Comment by zarino** [comment]
Thanks @struan for spotting the hover bug! @lucascumsille I’ve added it to https://github.com/mysociety/caps/issues/240

@struan do you want to squash and merge this? Or shall I?

**Comment by struan** [comment]
Feel free to go ahead :)

**Pull request merged**
