### PR TITLE
Open Graph preview for Councils

### LINKED ISSUE #517: Social media / Open Graph graphics for Scorecards pages
At the very least, we’ll want an updated Open Graph image with the [new Action Scorecards branding](https://github.com/mysociety/caps/issues/511). Last time round, we used the same image on all pages of the site, including the council pages.

But it would also be good to investigate the possibility of…

### 1. Individualised Open Graph image for each council page

Could show the council’s name, overall score, and even whether they were a "top scorer" (or whatever) amongst councils of their type. Our research repo does this already, eg: [creating a custom OpenGraph image when you link to a paragraph of text](https://research.mysociety.org/html/prototyping-rental-energy/l/1.4.ar58g.3a4x6.c94ps.k7-d-.html). (The research site generates these images _in advance_, using Selenium to take screenshots of a webpage, [as Github does](https://github.blog/2021-06-22-framework-building-open-graph-images/). We could potentially use something like https://github.com/simonw/shot-scraper for this too.)

### 2. Different Open Graph image for each section page

Could show the section name, and maybe the top few scorers … but which council type? (We could swap the Open Graph image when the user switches between council types on the section page.)

### 3. Fully DIY "generate and download your own Open Graph image" feature

CEUK point to https://www.greennewdealuk.org/campaigns/green-jobs-take-action/ as an example – where you pick your council from a list, and pre-populates an image (via JavaScript Canvas API) that you can download and share.

Ultimately, this is the same as Option 1, except with the addition that the image is available to download, rather than just being hidden in the Open Graph tags.

### 4. Custom infographics for CEUK to share manually, on social media

CEUK point to https://cleancitiescampaign.org/ranking-2022-edition/ (scroll down to "Infographics" section) as an example. I guess we could do this. Would need to take a steer from CEUK on what points they want to draw out from the data. So far, they’ve suggested "X council type do better, or councils in X region do better, or X section scores better by X council types/regions".

### PR DESCRIPTION
**Pull request by zarino**
Fixes #517.

## TODO:

- [x] Council preview page
- [x] Council Overall top performer
- [x] Section preview page
- [x] Section Top performer
- [x] Static fallback image for all other pages (add to `base.html` `<head>`)
- [x] Script for screenshotting every council and section page with https://github.com/simonw/shot-scraper

## WIP so far:

Screen Shot 2023-09-22 at 17 42 33

### CODE REVIEW

**Comment by lucascumsille** [comment]
Current state:

### Council
Screenshot 2023-09-28 at 08 23 37
Screenshot 2023-09-28 at 08 23 28

### Section
OPTION 1

Screenshot 2023-09-28 at 08 24 41

OPTION 2
Screenshot 2023-09-28 at 08 25 00

**Comment by lucascumsille** [comment]
Preview for commit [Open Graph preview for section top perfomer](https://github.com/mysociety/caps/pull/559/commits/168e99d8be9cf30956918c0c167fcf88a574b937)

Screenshot 2023-09-28 at 09 33 01
Screenshot 2023-09-28 at 09 32 57

**Comment by zarino** [comment]
Only comments I’d make on these:

Screenshot 2023-09-28 at 11 26 00

Have you tested how this will work for councils with the longest names? I assume the name will break onto two lines. Is there enough vertical space for that, now there’s a "Top performer" label in the way?

Screenshot 2023-09-28 at 11 26 17

Why so tight up against the side? I’d at least line it up with the right edge of the Scorecards logo above…

Screenshot 2023-09-28 at 11 29 49

**Comment by lucascumsille** [comment]
### Council preview page

Screenshot 2023-10-02 at 07 24 22
Screenshot 2023-10-02 at 07 24 26

### Council Overall top performer

Screenshot 2023-10-02 at 06 39 17
Screenshot 2023-10-02 at 06 39 25


 ### Section preview page

Screenshot 2023-10-02 at 11 30 42


### Section Top performer

Screenshot 2023-10-02 at 06 39 17
Screenshot 2023-10-02 at 06 39 25

 ### Static fallback image for all other pages (add to base.html <head>)

fallback

**Comment by lucascumsille** [comment]
@zarino I left the previews in the comment above

**Comment by lucascumsille** [comment]
Screenshot 2023-10-02 at 14 52 49
Screenshot 2023-10-02 at 14 50 51
Screenshot 2023-10-02 at 14 50 36
Screenshot 2023-10-02 at 14 50 13

**Comment by lucascumsille** [comment]
@zarino I think we can move ahead with this ticket. CEUK gave their approval.

Frame 679

**Comment by zarino** [comment]
Two small things @lucascumsille:

- In screenshot *C - council preview*, what do you think about making the "reversed out" text in the table ("Overall score", "54%") a darker shade of the green background colour, rather than a darker purple, so it matches the background?
- In screenshot *D - section preview*, should the table header cell "Average" read "Average score" instead? (To match "Overall score" on the council preview page)

I assume these all look ok in square (Instagram) format too? (That’s _assuming_ we still want to genereate square versions, to share in the Google Drive folder that CEUK will be publishing.)

**Comment by lucascumsille** [comment]
@zarino I have included the feedback above =)
I think Instagram should be working now:

Frame 680

**Comment by lucascumsille** [comment]
@zarino I'll add a commit for option C. The table looks weird when the council is high scoring a section.

**Comment by lucascumsille** [comment]
@zarino I think we are finally there. I added also a commit to fix the odd vertical spacing when there is no "High scoring" badge below or above h1.

Frame 680

**Comment by zarino** [comment]
@struan @lucascumsille I’ve just pushed a bunch of improvements / simplifications to this branch, and generated a full set of 1200x630 and 1000x1000 images and hand-checked that they all look ok.

My instinct would be to squash this whole branch into a single commit – there’s been so much back and forth, and I don’t think there’s much need for us to keep the commits separate for future reference.

@struan I’ll leave to you to squash and merge.

**Comment by zarino** [comment]
Oh damn, one thing I’ve just realised is still missing from this @struan @lucascumsille is actually _using_ the generated council/section images in `<meta property="og:image">` tags on the council/section pages. Looks like the simplest way to do this will be to:

- Copy the generated 1200x630 images into `/scoring/static/scoring/img/og-images/…` or something, and commit them. No need to retain the council_type folder hierarchy, that’s just for the images we’ll be uploading to Google Drive.
- Define an `og_image_path` context variable inside the `CouncilView` and `SectionView`, which will be something like `context["og_image_path"] = f"/scoring/static/scoring/img/og-images/{council.slug}.png"`? (and `{section.code}`, obviously)

**Pull request merged**
