### PR TITLE
Methodology page

### PR DESCRIPTION
**Pull request by lucascumsille**
Fixes: #541 
Updated methodology page copy. According to this document:
https://docs.google.com/document/d/1W6onpYh5B2Br7v6PUTV8OUpRu-ehNc3R24DZaTUKOqg/edit

Preview here:

https://github.com/mysociety/caps/assets/13790153/556cce6e-41de-47af-ab07-4991b3b5118d

### CODE REVIEW

**Review by zarino — APPROVED** [review]
Seems fine. One question, though:

@lucascumsille is it intentional that the "Section weightings" heading and tables appear twice? (Once immediately below the "Question criteria > See the questions" section, and then once again, much further down the page, in the "Scorecard Sections Summary and Weighting" section). I note that this first `<h2 id="section-weightings">Section weightings</h2>` doesn’t appear in the subnav either.

Maybe this is how CEUK have given it to us, in which case, let’s leave it and discuss with them tomorrow. But just mentioning in case it’s not.

**Comment by lucascumsille** [comment]
> Seems fine. One question, though:
> 
> @lucascumsille is it intentional that the "Section weightings" heading and tables appear twice? (Once immediately below the "Question criteria > See the questions" section, and then once again, much further down the page, in the "Scorecard Sections Summary and Weighting" section). I note that this first `<h2 id="section-weightings">Section weightings</h2>` doesn’t appear in the subnav either.
> 
> Maybe this is how CEUK have given it to us, in which case, let’s leave it and discuss with them tomorrow. But just mentioning in case it’s not.

@zarino That's how they have it in their methodology document.

**Comment by zarino** [comment]
> @zarino That's how they have it in their methodology document.

Ok! Let’s leave it in, then, and ask them about it next week.

**Comment by lucascumsille** [comment]
Just in @zarino This has been merge already.

**Comment by zarino** [comment]
Rebased and merged into `scorecards-2023` as 9e401b365a0c724f4a57d5cf2a23e90fce424c87

**Pull request closed without merging**
